name: Backend CI

on:
  pull_request:
    paths:
    - 'backend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['5.0']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: test-rs
        mongodb-port: 27017
    - name: Install Dependencies
      run: yarn install
      working-directory: ./backend
    - name: Run Tests
      env: 
        TEST_MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
      run: yarn test:ci --passWithNoTests
      working-directory: ./backend
    - name: Run Linter
      run: yarn lint
      working-directory: ./backend